# Generated by Django 4.1 on 2022-12-22 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fechainscripcion', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('reservada', 'RESRVADA'), ('completada', 'COMPLETADA'), ('anulada', 'ANULADA'), ('no asiste', 'NO ASISTE')], max_length=20)),
                ('observacion', models.TextField(blank=True, max_length=150)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NASHEAPP.institucion')),
            ],
        ),
    ]
